server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/IdeaProjects/orlikapp/config-properties
          #          uri: https://gitlab.com/orlik-api/config-properties.git
          clone-on-start: true
  security:
    user:
      name: admin
      password: admin